"""Phase 7 — fMP4 HLS playlists, TS HLS variant.

The DASH package produced by infinite_streaming_encoder.packager already has all the
media bytes we need. This module adds:

- Phase 7: generate HLS master + per-variant playlists from the DASH
  package (fMP4 segments). Reuses `infinite_streaming_encoder.manifests.hls_from_dash`.

- Phase 7b (optional): produce a parallel MPEG-TS HLS package from
  the same variant MP4s, for older clients. Skipped unless the caller
  asks for `--hls-format ts|both`.

Phase 6 used to live here: a walk over every `.m4s` writing a `.byteranges` JSON
sidecar beside it. Those files are no longer produced (#282) — the fragment
index now ships inside manifest.mpd as per-fragment @mediaRange, and the HLS
playlists carry it as EXT-X-PART. Both are generated by walking the media
directly (manifests._segment_fragments), so nothing needed the sidecars to be on
disk; they were 728 extra files per rung serving as an intermediate format
between two phases of the same program.
"""
from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path

from infinite_streaming_encoder.audio import AAC_BITRATE, AAC_SAMPLE_RATE
from infinite_streaming_encoder.manifests import hls_from_dash as _hls_from_dash


# ---------------------------------------------------------------------------
# Phase 7 — fMP4 HLS playlists
# ---------------------------------------------------------------------------

def generate_fmp4_hls(package_dir: Path) -> bool:
    """Generate master.m3u8 + per-variant playlists in `package_dir`.

    Playlists embed EXT-X-PART tags per fragment for LL-HLS; the fragment
    offsets/lengths and the per-fragment INDEPENDENT flag come from walking the
    .m4s boxes. INDEPENDENT is why HLS reads the media rather than the manifest:
    DASH's @mediaRange carries no independence bit.
    """
    return _hls_from_dash(package_dir)


# ---------------------------------------------------------------------------
# Phase 7b — TS HLS variant (optional, for legacy clients)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class TsHlsSpec:
    tmp_dir: Path              # holds {codec}_{label}.mp4 + audio.mp4
    ts_output_dir: Path        # top-level dir for the TS package
    codec: str
    labels: tuple[str, ...]    # rung labels ("1080p", "1080p_1", ...)
    segment_duration_s: float
    include_audio: bool


class HlsError(RuntimeError):
    pass


def _run_ffmpeg_hls(input_file: Path, out_dir: Path, segment_duration: float,
                    reencode_audio: bool = False) -> None:
    """Produce TS segments + playlist.m3u8 from one MP4 via ffmpeg's HLS muxer."""
    out_dir.mkdir(parents=True, exist_ok=True)
    cmd = ["ffmpeg", "-y", "-i", str(input_file)]
    if reencode_audio:
        # Re-encode audio to AAC so segment boundaries align exactly;
        # -c copy can drift on fractional-frame sources. Params come from
        # `audio` rather than being restated here — this path fed the SAME
        # ladder from a second literal, so tuning one format's audio and not
        # the other's produced no error anywhere (#296).
        cmd += ["-c:a", "aac", "-b:a", AAC_BITRATE, "-ar", AAC_SAMPLE_RATE]
    else:
        cmd += ["-c", "copy"]
    cmd += [
        "-f", "hls",
        "-hls_time", str(segment_duration),
        "-hls_segment_type", "mpegts",
        "-hls_segment_filename", str(out_dir / "segment_%03d.ts"),
        "-hls_playlist_type", "vod",
    ]
    if reencode_audio:
        cmd += ["-hls_flags", "independent_segments"]
    cmd += [
        str(out_dir / "playlist.m3u8"),
        "-loglevel", "warning", "-stats",
    ]
    try:
        subprocess.run(cmd, check=True)
    except subprocess.CalledProcessError as e:
        raise HlsError(f"ffmpeg HLS muxer failed for {input_file} ({e.returncode})") from e


def generate_ts_hls(spec: TsHlsSpec) -> Path:
    """Produce a complete TS HLS package mirroring the fMP4 tiers.

    Layout:
        <ts_output_dir>/
            <res>/segment_NNN.ts, <res>/playlist.m3u8   (per tier)
            audio/segment_NNN.ts, audio/playlist.m3u8   (if audio)
            master.m3u8

    Master playlist writing is deferred to the caller for now — bash's
    TS master had its own peculiarities (different CODECS strings) and
    matching those exactly requires probing the encoded MP4s. That's
    a later-session polish; for now this returns the dir and the
    caller owns master.m3u8.
    """
    spec.ts_output_dir.mkdir(parents=True, exist_ok=True)

    for label in spec.labels:
        source_mp4 = spec.tmp_dir / f"{spec.codec}_{label}.mp4"
        if not source_mp4.is_file():
            continue
        _run_ffmpeg_hls(
            source_mp4, spec.ts_output_dir / label, spec.segment_duration_s,
        )

    if spec.include_audio:
        audio_mp4 = spec.tmp_dir / "audio.mp4"
        if audio_mp4.is_file():
            _run_ffmpeg_hls(
                audio_mp4, spec.ts_output_dir / "audio", spec.segment_duration_s,
                reencode_audio=True,
            )

    return spec.ts_output_dir
